name: Home
version: "5.1"
main: com.nokhoon.home.PluginMain
description: home sweet home
api-version: "1.20"
author: "0x0804ac"
commands:
  home:
    description: Manage your favorite places to teleport to
    usage: /home <get|set|go|remove> <id>