name: Home
version: "4.6"
main: com.nokhoon.home.PluginMain
description: home sweet home
api-version: 1.19
author: "0x0804ac"
commands:
  home:
    description: manage your favorite location
    usage: /home <get|set|go|remove> <id>